# Generated by Django 3.2.9 on 2022-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recon',
            name='photo',
        ),
        migrations.AddField(
            model_name='recon',
            name='binary_photo',
            field=models.ImageField(blank=True, null=True, upload_to='binary_photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recon',
            name='blur_photo',
            field=models.ImageField(blank=True, null=True, upload_to='blur_photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recon',
            name='gray_photo',
            field=models.ImageField(blank=True, null=True, upload_to='gray_photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recon',
            name='ori_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ori_photos/%Y/%m/%d/'),
        ),
    ]
