# Generated by Django 3.2.9 on 2022-06-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0002_auto_20220604_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recon',
            name='blur_photo',
        ),
        migrations.AddField(
            model_name='recon',
            name='final_photo',
            field=models.ImageField(blank=True, null=True, upload_to='final_photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recon',
            name='morpho_photo',
            field=models.ImageField(blank=True, null=True, upload_to='morpho_photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recon',
            name='smoothed_photo',
            field=models.ImageField(blank=True, null=True, upload_to='smoothed_photos/%Y/%m/%d/'),
        ),
    ]
